//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Addon_Messem.FORMS.Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Addon_Messem.FORMS.Recursos.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select top 1 ItemCode from OITM.
        /// </summary>
        internal static string BuscaItens_Empresa {
            get {
                return ResourceManager.GetString("BuscaItens_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select top 1 CardCode from OINV.
        /// </summary>
        internal static string BuscaVendas_Empresa {
            get {
                return ResourceManager.GetString("BuscaVendas_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select *  from &quot;@DUO_PARAMCON&quot;.
        /// </summary>
        internal static string EmpresasConsolidadoras {
            get {
                return ResourceManager.GetString("EmpresasConsolidadoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from &quot;&quot;&quot; &amp; rstbases.Fields.Item(&quot;u_bd&quot;).Value &amp; &quot;&quot;&quot;.&quot;&quot;OPRC&quot;&quot; where &quot;&quot;DimCode&quot;&quot; = 1.
        /// </summary>
        internal static string ImportarCC {
            get {
                return ResourceManager.GetString("ImportarCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from  
        ///
        ///&quot;&quot;&quot; &amp; rstbases.Fields.Item(&quot;U_BD&quot;).Value &amp; &quot;&quot;&quot;.&quot;&quot;OJDT&quot;&quot; a  
        ///
        ///where   
        ///
        ///a.&quot;&quot;TransId&quot;&quot; not in (select iFnull(&quot;&quot;U_IDTRAN&quot;&quot;,0) from ojdt where cast(&quot;&quot;U_IDBD&quot;&quot; as int)=cast(&apos;&quot; &amp; rstbases.Fields.Item(&quot;U_ID&quot;).Value &amp; &quot;&apos; as int)) &quot;.
        /// </summary>
        internal static string ImportarLC {
            get {
                return ResourceManager.GetString("ImportarLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select * from &quot;&quot;&quot; &amp; rstbases.Fields.Item(&quot;u_bd&quot;).Value &amp; &quot;&quot;&quot;.&quot;&quot;OACT&quot;&quot; where &quot;&quot;Levels&quot;&quot;&gt;1 And &quot;&quot;AcctCode&quot;&quot; Not In (Select &quot;&quot;AcctCode&quot;&quot; from oact)&quot;.
        /// </summary>
        internal static string ImportarPC {
            get {
                return ResourceManager.GetString("ImportarPC", resourceCulture);
            }
        }
    }
}
